### ISSUE TITLE
Outdated Mending Patch

### ISSUE THREAD

**Issue by notfood** [XeoNovaDan/SurvivalTools#2]
Mending had a huge rework underneath.

In the patch it needs to be changed from MendAndRecycle.Worker to MendAndRecycle.RecipeWorkerWithJob_Mend

Alternatively, use MendBase as ParentName for future proof.

Please, make sure you have the filter with a health range from 0 to 99 so they don't repeat the job.
```xml
<AllowedHitPointsPercents><min>0.00</min><max>0.99</max></AllowedHitPointsPercents>
```

**Comment by XeoNovaDan** [comment]
Fixed. Thanks for informing me!
